### ISSUE TITLE
Strange issue upon server startup

### ISSUE THREAD

**Issue by Deathstreams** [gsand/mark2#100]
I can't even describe what is going on, I'll just post the outpot ._.
```
deathstreams@server:/home/servers$ mark2 start factions
2018-06-10 19:24:15 # mark2 starting...
2018-06-10 19:24:16 # starting factions
2018-06-10 19:24:16 # jar file: paperspigot-1.7.10-R0.1-SNAPSHOT.jar
2018-06-10 19:24:16 # pid: 15598
2018-06-10 19:24:16 # jvm options: -XX:+UseFastAccessorMethods -Xms128M -Xmx384M -Djline.terminal=jline.UnixTerminal -XX:MaxGCPauseMillis=20 -XX:+AggressiveOpts -XX:UseSSE=3 -XX:+UseG1GC
2018-06-10 19:24:16 | [RAW] Upon execvpe java ['java', '-XX:+UseFastAccessorMethods', '-Xms128M', '-Xmx384M', '-Djline.terminal=jline.UnixTerminal', '-XX:MaxGCPauseMillis=20', '-XX:+AggressiveOpts', '-XX:UseSSE=3', '-XX:+UseG1GC', '-jar', 'paperspigot-1.7.10-R0.1-SNAPSHOT.jar', 'nogui'] in environment id 94868703085920
2018-06-10 19:24:16 | [RAW] :Traceback (most recent call last):
2018-06-10 19:24:16 | [RAW]   File "/home/deathstreams/.local/lib/python2.7/site-packages/twisted/internet/process.py", line 420, in _fork
2018-06-10 19:24:16 | [RAW]     executable, args, environment)
2018-06-10 19:24:16 | [RAW]   File "/home/deathstreams/.local/lib/python2.7/site-packages/twisted/internet/process.py", line 466, in _execChild
2018-06-10 19:24:16 | [RAW]     os.execvpe(executable, args, environment)
2018-06-10 19:24:16 | [RAW]   File "/usr/lib/python2.7/os.py", line 355, in execvpe
2018-06-10 19:24:16 | [RAW]     _execvpe(file, args, env)
2018-06-10 19:24:16 | [RAW]   File "/usr/lib/python2.7/os.py", line 382, in _execvpe
2018-06-10 19:24:16 | [RAW]     func(fullname, *argrest)
2018-06-10 19:24:16 | [RAW] OSError: [Errno 2] No such file or directory
2018-06-10 19:24:16 # fatal error: A process has ended with a probable error condition: process ended with exit code 1.
2018-06-10 19:24:16 # mark2 stopped.
deathstreams@server:/home/servers$
```

**Comment by Deathstreams** [comment]
Solved - Java was not properly installed on the machine.
