### ISSUE TITLE
Server Start/Attach Error

### ISSUE THREAD

**Issue by bigbluu722** [gsand/mark2#106]
% mark2 start test
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/local/lib/mark2/mk2/services/process.py", line 107, in server_starting
            self.stat_process.start(self.parent.config['java.ps.interval'])
          File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 194, in start
            self()
          File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/local/lib/mark2/mk2/services/process.py", line 166, in update_stat
            except psutil.error.NoSuchProcess:
        exceptions.AttributeError: 'module' object has no attribute 'error'

Pastebin [here](https://pastebin.com/QxfLBA6y) if formatting fails again.

Seem to be receiving this error when starting a server, not sure what would be causing this seeing as everything seems to be installed correctly. Any help would be appreciated.

**Comment by Column01** [comment]
I know bigbluu, we fixed this ages ago... cleaning up issues
