### ISSUE TITLE
Errno 1 - Operation not permitted

### ISSUE THREAD

**Issue by ediTv2** [gsand/mark2#11]
I can't seem to resolve this issue. Any help would be appreciated! :)

xxx@xxxxx:/home/minecraft/hub$ mark2 start

Traceback (most recent call last):
  File "/usr/local/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/usr/local/share/mark2/mk2/launcher.py", line 611, in main
    command.start()
  File "/usr/local/share/mark2/mk2/launcher.py", line 125, in start
    b.do_start(self)
  File "/usr/local/share/mark2/mk2/launcher.py", line 150, in do_start
    os.remove(path)
OSError: [Errno 1] Operation not permitted: '/tmp/mark2/hub.pid'

**Comment by gsand** [comment]
Delete /tmp/mark2/hub.pid
