### ISSUE TITLE
Mark2 wont start all of a sudden? UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by TomLewis** [gsand/mark2#124]
Ive been starting/stopping this server all day, and suddenly out of the blue mark2 just will not boot?
But its working perfectly fine booting up another server on the same machine.
What on earth is it doing? Before this I made a symbolic link to folder in one of the plugin folders, which ive done for a bunch of other servers running fine.

```user@machine:~/server/play$ mark2 start
2020-12-05 15:33:55 # mark2 starting...
2020-12-05 15:33:55 # Traceback (most recent call last):
2020-12-05 15:33:55 #   File "/usr/mark2/mk2/manager.py", line 38, in startup
2020-12-05 15:33:55 #     self.really_start()
2020-12-05 15:33:55 #   File "/usr/mark2/mk2/manager.py", line 88, in really_start
2020-12-05 15:33:55 #     self.properties = properties.load(properties.Mark2Properties, open_resource('resources/server.default.properties'), 'server.properties')
2020-12-05 15:33:55 #   File "/usr/mark2/mk2/properties.py", line 13, in load
2020-12-05 15:33:55 #     o = cls(f, o)
2020-12-05 15:33:55 #   File "/usr/mark2/mk2/properties.py", line 115, in __init__
2020-12-05 15:33:55 #     v = parse(v)
2020-12-05 15:33:55 #   File "/usr/mark2/mk2/properties.py", line 80, in parse
2020-12-05 15:33:55 #     out += c
2020-12-05 15:33:55 # UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
2020-12-05 15:33:55 #
2020-12-05 15:33:55 # mark2 stopped.
```

**Comment by TomLewis** [comment]
I figured this out myself.

Deleted the server.properties and created a new one from scratch, no idea what the issue was.
