### ISSUE TITLE
Mark2 Attach

### ISSUE THREAD

**Issue by simon445561** [gsand/mark2#13]
I get this error when attaching.
I am using Debian 7

Traceback (most recent call last):
  File "/usr/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/usr/mark2/mk2/launcher.py", line 611, in main
    command.start()
  File "/usr/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/mark2/mk2/launcher.py", line 506, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/usr/mark2/mk2/user_client.py", line 456, in __init__
    self.ui = UI(self.config.get_palette(), self.get_players, self.run_command, self.switch_server, self.connect_to_server, self.config.get_player_actions(), self.config.get_player_reasons())
  File "/usr/mark2/mk2/user_client.py", line 211, in __init__
    self.build()
  File "/usr/mark2/mk2/user_client.py", line 217, in build
    g_head         = urwid.AttrMap(urwid.Columns((('weight', 3, self.g_servers), self.g_users)), 'head')
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1092, in __init__
    if focus_column is None and w.selectable():
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1411, in selectable
    return self.widget_list[self.focus_col].selectable()
IndexError: list index out of range

**Comment by simon445561** [comment]
Found the issue wrong version of urwid run pip install urwid --upgrade to fix.
