### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by paperrain** [gsand/mark2#27]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/mark2/mk2/launcher.py", line 506, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/usr/mark2/mk2/user_client.py", line 466, in __init__
    t.start(self.config.get_interval('users'))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 163, in start
    self()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 208, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/mark2/mk2/user_client.py", line 512, in update_users
    self.system_users.update_users()
  File "/usr/mark2/mk2/user_client.py", line 380, in update_users
    for u in psutil.get_users():
exceptions.AttributeError: 'module' object has no attribute 'get_users'

**Comment by gsand** [comment]
Is there any more information you would like to provide?

**Comment by paperrain** [comment]
My SO:
Ubuntu: 12.04 Server

**Comment by gsand** [comment]
Does it happen every time?

**Comment by paperrain** [comment]
Yes

**Comment by gsand** [comment]
are you using the appropriate version of psutil?
