### ISSUE TITLE
Error when starting mark2

### ISSUE THREAD

**Issue by RafaAro** [gsand/mark2#59]
Hi, I'm getting an error when doing mark2 start only when there are none of the mc servers started:

> 2016-07-12 03:45:27 # mark2 starting...
2016-07-12 03:45:27 # starting ml01
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/mark2/mk2/services/process.py", line 107, in server_starting
            self.stat_process.start(self.parent.config['java.ps.interval'])
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 194, in start
            self()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/mark2/mk2/services/process.py", line 165, in update_stat
            except psutil.error.NoSuchProcess:
        exceptions.AttributeError: 'module' object has no attribute 'error'
2016-07-12 03:45:27 # pid: 27603
2016-07-12 03:45:27 # jvm options: -Xms1G -Xmx1G -Djline.terminal=jline.UnsupportedTerminal -XX:MaxPermSize=128M
2016-07-12 03:45:27 | [RAW] OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
2016-07-12 03:45:27 | [RAW] Loading libraries, please wait...
2016-07-12 03:45:29 | Starting minecraft server version 1.10.2
2016-07-12 03:45:29 | Loading properties
2016-07-12 03:45:29 | Default game type: SURVIVAL
2016-07-12 03:45:29 | This server is running CraftBukkit version git-Spigot-7745d45-02d704b (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
2016-07-12 03:45:29 | Server Ping Player Sample Count: 12
2016-07-12 03:45:29 | Using 4 threads for Netty based IO
2016-07-12 03:45:29 | Debug logging is disabled
2016-07-12 03:45:29 | Generating keypair
2016-07-12 03:45:29 | Starting Minecraft server on *:25565
2016-07-12 03:45:29 | Using epoll channel type
2016-07-12 03:45:32 | [WARN] Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
2016-07-12 03:45:33 | **** Beginning UUID conversion, this may take A LONG time ****
2016-07-12 03:45:33 | Preparing level "world"
2016-07-12 03:45:33 | -------- World Settings For [world] --------
2016-07-12 03:45:33 | Mob Spawn Range: 4
2016-07-12 03:45:33 | Cactus Growth Modifier: 100%
2016-07-12 03:45:33 | Cane Growth Modifier: 100%
2016-07-12 03:45:33 | Melon Growth Modifier: 100%
2016-07-12 03:45:33 | Mushroom Growth Modifier: 100%
2016-07-12 03:45:33 | Pumpkin Growth Modifier: 100%
2016-07-12 03:45:33 | Sapling Growth Modifier: 100%
2016-07-12 03:45:33 | Wheat Growth Modifier: 100%
2016-07-12 03:45:33 | NetherWart Growth Modifier: 100%
2016-07-12 03:45:33 | Entity Activation Range: An 32 / Mo 32 / Mi 16
2016-07-12 03:45:33 | Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
2016-07-12 03:45:33 | Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
2016-07-12 03:45:33 | Random Lighting Updates: false
2016-07-12 03:45:33 | Structure Info Saving: true
2016-07-12 03:45:33 | Max Entity Collisions: 8
2016-07-12 03:45:33 | Custom Map Seeds:  Village: 10387312 Feature: 14357617
2016-07-12 03:45:33 | Max TNT Explosions: 100
2016-07-12 03:45:33 | Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
2016-07-12 03:45:33 | Item Despawn Rate: 6000
2016-07-12 03:45:33 | Item Merge Radius: 2.5
2016-07-12 03:45:33 | Arrow Despawn Rate: 1200
2016-07-12 03:45:33 | Allow Zombie Pigmen to spawn from portal blocks: true
2016-07-12 03:45:33 | View Distance: 10
2016-07-12 03:45:33 | Zombie Aggressive Towards Villager: true
2016-07-12 03:45:33 | Experience Merge Radius: 3.0
2016-07-12 03:45:33 | Nerfing mobs spawned from spawners: false
2016-07-12 03:45:33 | -------- World Settings For [world_nether] --------
2016-07-12 03:45:33 | Mob Spawn Range: 4
2016-07-12 03:45:33 | Cactus Growth Modifier: 100%
2016-07-12 03:45:33 | Cane Growth Modifier: 100%
2016-07-12 03:45:33 | Melon Growth Modifier: 100%
2016-07-12 03:45:33 | Mushroom Growth Modifier: 100%
2016-07-12 03:45:33 | Pumpkin Growth Modifier: 100%
2016-07-12 03:45:33 | Sapling Growth Modifier: 100%
2016-07-12 03:45:33 | Wheat Growth Modifier: 100%
2016-07-12 03:45:33 | NetherWart Growth Modifier: 100%
2016-07-12 03:45:33 | Entity Activation Range: An 32 / Mo 32 / Mi 16
2016-07-12 03:45:33 | Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
2016-07-12 03:45:33 | Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
2016-07-12 03:45:33 | Random Lighting Updates: false
2016-07-12 03:45:33 | Structure Info Saving: true
2016-07-12 03:45:33 | Max Entity Collisions: 8
2016-07-12 03:45:33 | Custom Map Seeds:  Village: 10387312 Feature: 14357617
2016-07-12 03:45:33 | Max TNT Explosions: 100
2016-07-12 03:45:33 | Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
2016-07-12 03:45:33 | Item Despawn Rate: 6000
2016-07-12 03:45:33 | Item Merge Radius: 2.5
2016-07-12 03:45:33 | Arrow Despawn Rate: 1200
2016-07-12 03:45:33 | Allow Zombie Pigmen to spawn from portal blocks: true
2016-07-12 03:45:33 | View Distance: 10
2016-07-12 03:45:33 | Zombie Aggressive Towards Villager: true
2016-07-12 03:45:33 | Experience Merge Radius: 3.0
2016-07-12 03:45:33 | Nerfing mobs spawned from spawners: false
2016-07-12 03:45:33 | -------- World Settings For [world_the_end] --------
2016-07-12 03:45:33 | Mob Spawn Range: 4
2016-07-12 03:45:33 | Cactus Growth Modifier: 100%
2016-07-12 03:45:33 | Cane Growth Modifier: 100%
2016-07-12 03:45:33 | Melon Growth Modifier: 100%
2016-07-12 03:45:33 | Mushroom Growth Modifier: 100%
2016-07-12 03:45:33 | Pumpkin Growth Modifier: 100%
2016-07-12 03:45:33 | Sapling Growth Modifier: 100%
2016-07-12 03:45:33 | Wheat Growth Modifier: 100%
2016-07-12 03:45:33 | NetherWart Growth Modifier: 100%
2016-07-12 03:45:33 | Entity Activation Range: An 32 / Mo 32 / Mi 16
2016-07-12 03:45:33 | Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
2016-07-12 03:45:33 | Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
2016-07-12 03:45:33 | Random Lighting Updates: false
2016-07-12 03:45:33 | Structure Info Saving: true
2016-07-12 03:45:33 | Max Entity Collisions: 8
2016-07-12 03:45:33 | Custom Map Seeds:  Village: 10387312 Feature: 14357617
2016-07-12 03:45:33 | Max TNT Explosions: 100
2016-07-12 03:45:33 | Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
2016-07-12 03:45:33 | Item Despawn Rate: 6000
2016-07-12 03:45:33 | Item Merge Radius: 2.5
2016-07-12 03:45:33 | Arrow Despawn Rate: 1200
2016-07-12 03:45:33 | Allow Zombie Pigmen to spawn from portal blocks: true
2016-07-12 03:45:33 | View Distance: 10
2016-07-12 03:45:33 | Zombie Aggressive Towards Villager: true
2016-07-12 03:45:33 | Experience Merge Radius: 3.0
2016-07-12 03:45:33 | Nerfing mobs spawned from spawners: false
2016-07-12 03:45:33 | Preparing start region for level 0 (Seed: 5137845568094198117)
2016-07-12 03:45:34 | Preparing spawn area: 86%
2016-07-12 03:45:34 | Preparing start region for level 1 (Seed: 5137845568094198117)
2016-07-12 03:45:34 | Preparing start region for level 2 (Seed: 5137845568094198117)
2016-07-12 03:45:34 | Server permissions file permissions.yml is empty, ignoring it
2016-07-12 03:45:34 # mark2 started.

How can I fix this?

Thanks!

**Comment by gsand** [comment]
https://github.com/gsand/mark2/issues/64#issuecomment-246211149
