### ISSUE TITLE
Can't attach servers

### ISSUE THREAD

**Issue by Bonkozorus** [gsand/mark2#6]
Traceback (most recent call last):
  File "/usr/local/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/home/minecraft/mark2/mk2/launcher.py", line 611, in main
    command.start()
  File "/home/minecraft/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/home/minecraft/mark2/mk2/launcher.py", line 506, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/home/minecraft/mark2/mk2/user_client.py", line 456, in __init__
    self.ui = UI(self.config.get_palette(), self.get_players, self.run_command, self.switch_server, self.connect_to_server, self.config.get_player_actions(), self.config.get_player_reasons())
  File "/home/minecraft/mark2/mk2/user_client.py", line 211, in __init__
    self.build()
  File "/home/minecraft/mark2/mk2/user_client.py", line 217, in build
    g_head         = urwid.AttrMap(urwid.Columns((('weight', 3, self.g_servers), self.g_users)), 'head')
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1092, in __init__
    if focus_column is None and w.selectable():
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1411, in selectable
    return self.widget_list[self.focus_col].selectable()
IndexError: list index out of range

Got this when i try to mark2 attach, what's wrong?

**Comment by Bonkozorus** [comment]
Fixed it, my bad sorry.

**Comment by Bonkozorus** [comment]
https://github.com/mcdevs/mark2/issues/151
