### ISSUE TITLE
Exception with ~restart

### ISSUE THREAD

**Issue by rikai** [gsand/mark2#67]
Ran into this while running on arch in the way described in #66:

```
2016-09-10 12:00:01 # An event handler threw an exception:
2016-09-10 12:00:01 #   Callback: <bound method Shutdown.h_restart of <shutdown.Shutdown object at 0x782bde0a9350>>
2016-09-10 12:00:01 #   Event:
2016-09-10 12:00:01 #     class_name: Hook
2016-09-10 12:00:01 #     line: ~restart 5
2016-09-10 12:00:01 #     args: 5
2016-09-10 12:00:01 #     is_command: True
2016-09-10 12:00:01 #     name: restart
2016-09-10 12:00:01 #   Traceback (most recent call last):
2016-09-10 12:00:01 #     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
2016-09-10 12:00:01 #       result = g.send(result)
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/plugins/script.py", line 74, in execute_reduced
2016-09-10 12:00:01 #       handled = yield self.plugin.dispatch(events.Hook(line=cmd))
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/events/__init__.py", line 238, in dispatch
2016-09-10 12:00:01 #       d = self._next_event(event, event_list)
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/events/__init__.py", line 218, in _next_event
2016-09-10 12:00:01 #       r = maybeDeferred(callback, event)
2016-09-10 12:00:01 #   --- <exception caught here> ---
2016-09-10 12:00:01 #     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 137, in maybeDeferred
2016-09-10 12:00:01 #       result = f(*args, **kw)
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/plugins/shutdown.py", line 106, in h_restart
2016-09-10 12:00:01 #       warn_length, action, cancel = self.action_chain_cancellable(event.args, self.warn_restart, action, self.warn_cancel)
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/plugins/__init__.py", line 246, in action_chain_cancellable
2016-09-10 12:00:01 #       intervals = [self.parse_time(i) for i in spec.split(';')]
2016-09-10 12:00:01 #     File "/usr/local/share/mark2/mk2/plugins/__init__.py", line 282, in parse_time
2016-09-10 12:00:01 #       v = int(spec[:-1])
2016-09-10 12:00:01 #   exceptions.ValueError: invalid literal for int() with base 10: ''
```

**Comment by gsand** [comment]
did you run `~restart <symbol>`

Ideally, you should run `~restart` or `~restart 10s` or `~restart 5m;1m;30s;15s;10s;5s;4s;3s;2s;1s`

**Comment by gsand** [comment]
Ah, you ran `~restart 5` without stating seconds, minutes, etc

**Comment by rikai** [comment]
Ah yes, yes I did.

I had assumed it just defaulted to seconds, my bad!

Should still probably catch the exception, tell people their format is invalid and give an example of the default format though, i imagine.

**Comment by gsand** [comment]
Yeah
