### ISSUE TITLE
Server start error

### ISSUE THREAD

**Issue by wasder** [gsand/mark2#80]
I did a clean install on Debian server and get this when try to start a server.
```
mc@ns342643:~$ mark2 start Creative/
Traceback (most recent call last):
  File "/usr/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/usr/mark2/mk2/launcher.py", line 621, in main
    command.start()
  File "/usr/mark2/mk2/launcher.py", line 125, in start
    b.do_start(self)
  File "/usr/mark2/mk2/launcher.py", line 145, in do_start
    pid = int(fp.read())
ValueError: invalid literal for int() with base 10: ''

```

**Comment by evernife** [comment]
```
myuser@myhost:~$ mark2
Traceback (most recent call last):
  File "/usr/local/bin/mark2", line 3, in <module>
    from mk2.launcher import main
  File "/usr/local/share/mark2/mk2/launcher.py", line 14, in <module>
    from . import manager
  File "/usr/local/share/mark2/mk2/manager.py", line 5, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 23, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 24, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
```

**Comment by evernife** [comment]
well, this worked for me:


Try ```sudo pip install -U pyOpenSSL```

**Comment by wasder** [comment]
I still got this error on the latest commit. :\
```/usr/local/share/mark2$ ./mark2 attach
Traceback (most recent call last):
  File "./mark2", line 6, in <module>
    sys.exit(main())
  File "/usr/local/share/mark2/mk2/launcher.py", line 621, in main
    command.start()
  File "/usr/local/share/mark2/mk2/launcher.py", line 125, in start
    b.do_start(self)
  File "/usr/local/share/mark2/mk2/launcher.py", line 145, in do_start
    pid = int(fp.read())
ValueError: invalid literal for int() with base 10: ''
```

**Comment by evernife** [comment]
@wasder have you tried 

> sudo pip install -U pyOpenSSL

**Comment by wasder** [comment]
@evernife yes.

**Comment by Theepwner** [comment]
Hoping for fix!
