### ISSUE TITLE
exceptions.AttributeError: 'module' object has no attribute 'get_users'

### ISSUE THREAD

**Issue by Gino** [gsand/mark2#84]
Hi,

When I attach to a server and press CTRL + C, I get the following error:
`Traceback (most recent call last):
  File "/usr/mark2/mk2/launcher.py", line 506, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/usr/mark2/mk2/user_client.py", line 464, in __init__
    t.start(self.config.get_interval('users'))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 194, in                                                                                                                                                              start
    self()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in                                                                                                                                                              __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, i                                                                                                                                                             n maybeDeferred
    result = f(*args, **kw)
  File "/usr/mark2/mk2/user_client.py", line 510, in update_users
    self.system_users.update_users()
  File "/usr/mark2/mk2/user_client.py", line 378, in update_users
    for u in psutil.get_users():
exceptions.AttributeError: 'module' object has no attribute 'get_users'
`

Could anyone help me with this error? Thanks.

**Comment by evernife** [comment]
Try ```sudo pip install -U pyOpenSSL```

**Comment by evernife** [comment]
worked?
