### ISSUE TITLE
Debian 9 Install

### ISSUE THREAD

**Issue by OnlyBrakeForRainbows** [gsand/mark2#93]
I'm getting a load of errors and not familiar with python as such this is where I'm at currently:

` pip install requirements.txt `

`
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
`

So I installed the packages manually:

` pip install feedparser==5.1.3 psutil==0.6.1 pyOpenSSL==17.2.0 Twisted==13.0.0 urwid==1.3.1 `

They went through but running mark2 config gives:

`
Traceback (most recent call last):
  File "/usr/local/bin/mark2", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL==0.13' distribution was not found and is required by mark2
`

But I surely have the recommended version `pyOpenSSL==17.2.0` already installed? Just going around in circles now and hope someone can help. Python version is 2.7.13

**Comment by OnlyBrakeForRainbows** [comment]
Fixed install by:

Setup, link, clone the Mark2 package and install python packages:

` 
# git clone git://github.com/gsand/mark2.git /usr/local/share/mark2
# cd /usr/local/share/mark2
# ln -s /usr/local/share/mark2/mark2 /usr/local/bin/mark2
# pip install -r /usr/local/share/mark2/requirements.txt
`

Run the main Mark2 configuration setup:

` # mark2 config `

Thanks to [vemacs](https://gist.github.com/vemacs/5663144) gist here, I suspect either the symlink is wrong or something to do with python.
