### ISSUE TITLE
[Solved myself] Unknown error no new lines in console.

### ISSUE THREAD

**Issue by dyanakiev** [gsand/mark2#94]
Hello,
After i installed skript and some addons skquery, skellett
I got this error:
```
2017-12-24 15:16:55 | [Skript] Loaded a total of 79112 english aliases
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 257, in doRead
	    return fdesc.readFromFD(self.fd, self.dataReceived)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/fdesc.py", line 94, in readFromFD
	    callback(output)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 260, in dataReceived
	    self.proc.childDataReceived(self.name, data)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 899, in childDataReceived
	    self.proto.childDataReceived(name, data)
	  File "/usr/mark2/mk2/services/process.py", line 27, in childDataReceived
	    data = data.decode(self.locale)
	exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 42: ordinal not in range(128)
```

---
This is what i got in the real log after the error occur:
```
[15:16:55] [Server thread/INFO]: [Skript] Loaded a total of 79112 english aliases
[15:16:55] [Server thread/INFO]: [Skript]  ~ created by &    Peter G  ttinger aka Njol ~
[15:16:55] [Server thread/INFO]: [SkQuery] Enabling SkQuery v3.6.0-Lime
[15:16:55] [Server thread/INFO]: [skQuery] Snooping enabled from com.w00tmast3r.skquery.SkQuery
[15:16:55] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[15:16:55] [Server thread/INFO]: [skQuery] Finished snooping of SkQuery with 148 classes.
[15:16:55] [Server thread/INFO]: [skQuery] Beginning to process a total of 148 from SkQuery
[15:16:55] [Server thread/INFO]: [skQuery] Out of 148 classes, 144 classes were loaded from SkQuery
[15:16:55] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.9-SNAPSHOT;3721-fbd6f13
[15:16:55] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
```
So i believe ~ created by &    Peter G  ttinger aka Njol ~ those characters some how broke mark2. hmm?

**Comment by dyanakiev** [comment]
So i found a fix.
I edited /usr/mark2/mk2/services/process.py

data = data.decode(self.locale)
with
data = data.decode('utf8')
