### ISSUE TITLE
Unhandled error in Deferred

### ISSUE THREAD

**Issue by mfnalex** [gsand/mark2#96]
After a clean install on debian 9, I get this:

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/share/mark2/mk2/launcher.py", line 506, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/usr/local/share/mark2/mk2/user_client.py", line 464, in __init__
    t.start(self.config.get_interval('users'))
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 173, in start
    self()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/share/mark2/mk2/user_client.py", line 510, in update_users
    self.system_users.update_users()
  File "/usr/local/share/mark2/mk2/user_client.py", line 378, in update_users
    for u in psutil.get_users():
exceptions.AttributeError: 'module' object has no attribute 'get_users'
```

EDIT: It is working in debian 8.

**Comment by Column01** [comment]
I know this is super old, this is due to a dependency issue when installing the modules for mark2. At some point, `psutil` was updated and changed this function call to `psutil.users()`.

Please update to the latest mark2 following the install guide (basically a full reinstall) and this should go away
