### ISSUE TITLE
Server start error

### ISSUE THREAD

**Issue by ucraft02** [gsand/mark2#97]
`[root@server ~]# mark2 start hub
error: path does not exist: /root/hub
[root@server ~]# mark2 start hub
2018-02-07 22:00:33 # mark2 starting...
2018-02-07 22:00:34 # starting hub
2018-02-07 22:00:34 # jar file: spigot.jar
2018-02-07 22:00:34 # pid: 21403
2018-02-07 22:00:34 # jvm options: -Xmx512M -Djline.terminal=jline.UnsupportedTerminal
2018-02-07 22:00:34 | [RAW] Upon execvpe java ['java', '-Xmx512M', '-Djline.terminal=jline.UnsupportedTerminal', '-jar', 'spigot.jar', 'nogui'] in environment id 140531638230816
2018-02-07 22:00:34 | [RAW] :Traceback (most recent call last):
2018-02-07 22:00:34 | [RAW]   File "/usr/lib64/python2.7/site-packages/twisted/internet/process.py", line 420, in _fork
2018-02-07 22:00:34 | [RAW]     executable, args, environment)
2018-02-07 22:00:34 | [RAW]   File "/usr/lib64/python2.7/site-packages/twisted/internet/process.py", line 466, in _execChild
2018-02-07 22:00:34 | [RAW]     os.execvpe(executable, args, environment)
2018-02-07 22:00:34 | [RAW]   File "/usr/lib64/python2.7/os.py", line 353, in execvpe
2018-02-07 22:00:34 | [RAW]     _execvpe(file, args, env)
2018-02-07 22:00:34 | [RAW]   File "/usr/lib64/python2.7/os.py", line 380, in _execvpe
2018-02-07 22:00:34 | [RAW]     func(fullname, *argrest)
2018-02-07 22:00:34 | [RAW] OSError: [Errno 2] No such file or directory
2018-02-07 22:00:34 # fatal error: A process has ended with a probable error condition: process ended with exit code 1.
2018-02-07 22:00:34 # mark2 stopped.`

**Comment by Trikolon** [comment]
> [root@server ~]
Never ever run a user level application as root.

**Comment by ucraft02** [comment]
In wich user I musst run mark2?
